version: '2'
services:
    cmexodus-app:
        image: cmexodus
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cmexodus-postgresql:5432/CMExodus
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cmexodus-postgresql:
        extends:
            file: postgresql.yml
            service: cmexodus-postgresql
